### ISSUE TITLE
Text not showing fully

### ISSUE THREAD

**Issue by benstigsen** [imfunniee/gitfolio#1] opened 2019-05-09 11:54 UTC
When I load my site, the title of the repo cards don't fully show. This usually gets fixed when I refresh.

## Before refresh:  
![Screenshot_2019-05-09 BenTearzz(2)](https://user-images.githubusercontent.com/24865450/57451669-3c90e100-7262-11e9-86c2-a50a64d81336.png)

---

## After refresh:  
![Screenshot_2019-05-09 BenTearzz(1)](https://user-images.githubusercontent.com/24865450/57451448-9218be00-7261-11e9-873f-e5f663647970.png)

---

**Comment by imfunniee** [comment] 2019-05-09 12:19
hmm... your browser might be doing that.

**Comment by owen-roberts** [comment] 2019-05-09 12:52
I'm also experiencing this issue intermittently in the latest version of Firefox Developer Edition (v67.0b18). Doesn't seem to be happening in Chrome.

Title of the repo is "red-ball".

![image](https://user-images.githubusercontent.com/10622911/57454652-4239f700-7261-11e9-975c-c5473c67d00a.png)

**Comment by benstigsen** [comment] 2019-05-09 13:13
Yep, also using the latest version of Firefox, not the dev version though.

Doesn't seem to happen on Chrome here either.

**Comment by imfunniee** [comment] 2019-05-09 13:20
ye it seems like its happening only on firefox and not on chrome. 

I don't have developer edition but tested it on the latest stable version (Firefox 66.0.5 (64-bit)) and i'm not able to reproduce the issue.

btw is this happening on other sites too??

**Comment by benstigsen** [comment] 2019-05-09 14:16
This is the first time I'm seeing text being cut off like this. I cleared my cache and history, as well as went into incognito mode, but it still happens. When I go to @ORoberts221's site it also happens.

The last letter is there, but it gets covered by some color.

**Comment by imfunniee** [comment] 2019-05-12 13:04
gonna close this assuming its a browser (firefox) bug. if someone can RP it in chrome i'll open it again.

**Closed as completed by imfunniee** 2019-05-12 13:04 UTC
Labels: wait what
